#!/usr/bin/env node

const cli = require('commander');
const GitHub = require('github-api');
const { prerelease } = require('semver');
const { version } = require('./package');

function isPrerelease(version) {
  return !!prerelease(version);
}

function parseCli(cli, options, argv) {
  options.forEach(option => cli.option(option[0], option[1]));
  cli.parse(argv);
}

parseCli(cli, [
  ['-a --asset', 'Release asset'],
  ['-t --tag', 'Release tag']
], process.argv);

console.log('Options:');
console.log('Tag:', cli.tag);
console.log('Asset:', cli.asset);

const {
  GH_REF,
  GH_TOKEN,
  GIT_USER_NAME
} = process.env;
console.log(process.env);

const github = new GitHub({ token: GH_TOKEN });
const repo = github.getRepo(GIT_USER_NAME, GH_REF.split('/').pop());

repo.createRelease({
  name: cli.tag,
  prerelease: isPrerelease(version),
  tag_name: cli.tag
}, (error, result, request) => {
  if (error) {
    console.error(`Error: ${error}`);
    return;
  }
  console.log(`Result: ${result}`);
  console.log(`Request: ${request}`);
});
